<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>br.senac.sp.security.tokens</groupId>
	<artifactId>security-tokens</artifactId>
	<version>0.0.1</version>
	<packaging>jar</packaging>
	<name>security-tokens-jwt</name>
	<description>Provides JWT tokens for authenticating and executing essential requests in my projects.</description>

	<!--	<parent>-->
	<!--		<groupId>org.springframework.boot</groupId>-->
	<!--		<artifactId>spring-boot-starter-parent</artifactId>-->
	<!--		<version>3.4.3</version>-->
	<!--		<relativePath/> &lt;!&ndash; lookup parent from repository &ndash;&gt;-->
	<!--	</parent>-->

	<properties>
		<java.version>17</java.version>
		<!-- Define a codificação usada pelo compilador Java. -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<!-- Define a codificação para relatórios gerados pelo Maven. -->
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<spring-boot-starter-security.version>3.4.3</spring-boot-starter-security.version>
		<log4j-core.version>2.24.3</log4j-core.version>
		<log4j-api.version>2.24.3</log4j-api.version>
	</properties>

	<dependencies>

		<!-- Spring Web, Suporte a controladoresm, templates e Tomcat embutido-->
		<!-- Solucao para Cannot resolve symbol 'HandlerInterceptor' -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<!-- Removendo para utilizar a versao Log4J livre de vulnerabilidades -->
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Log4J2 -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j-core.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>${log4j-api.version}</version>
		</dependency>

		<!-- Vamos trabalhar com token, nao ha necessidade do Spring Boot Starter Security -->
		<!--		<dependency>-->
		<!--			<groupId>org.springframework.boot</groupId>-->
		<!--			<artifactId>spring-boot-starter-security</artifactId>-->
		<!--			<version>${spring-boot-starter-security.version}</version>-->
		<!--		</dependency>-->

		<!-- Spring Boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<version>3.4.3</version>
		</dependency>

		<!-- Tests -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<!--		<dependency>-->
		<!--			<groupId>org.springframework.security</groupId>-->
		<!--			<artifactId>spring-security-test</artifactId>-->
		<!--			<scope>test</scope>-->
		<!--		</dependency>-->

		<!-- JJWT for JWT handling -->
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.12.6</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.12.6</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.12.6</version>
			<scope>runtime</scope>
		</dependency>

	</dependencies>

	<!-- Se quiser utilizar a gestão de dependências do Spring Boot sem herdar do parent:-->
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>3.4.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<!-- Não inclua o spring-boot-maven-plugin, pois não precisa empacotar um fat jar -->
	<build>
		<plugins>
			<!--			<plugin>-->
			<!--				<groupId>org.springframework.boot</groupId>-->
			<!--				<artifactId>spring-boot-maven-plugin</artifactId>-->
			<!--			</plugin>-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
